[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/callback"
  to = "/callback.html"
  status = 200

[[redirects]]
  from = "/peso"
  to = "/peso.html"
  status = 200

[build.environment]
  SECRETS_SCAN_OMIT_PATHS = "callback.html,peso.html"
