[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/callback"
  to = "/pianoallenamento/callback.html"
  status = 200

[[redirects]]
  from = "/peso"
  to = "/pianoallenamento/peso.html"
  status = 200

[build.environment]
  SECRETS_SCAN_OMIT_PATHS = "pianoallenamento/callback.html,pianoallenamento/peso.html"
